<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Soins founir</title>
</head>
<body>
    <h1>Presentation des consultations effectués dans le service d'O.R.L</h1>
    <table>
    <tr>
        <td><h4>SERVICE D'ORL</h4></td>
        <td><h4>Acte</h4></td>
        <td><h4>Qté</h4></td>
        <td><h4>P.U(F CFA)</h4></td>
        <td><h4>Montant(F CFA)</h4></td>
    </tr>
    <tr>
       <td>INCISION CELLULITE</td>
       <td>K4</td>
       <td>30</td>
       <td>750</td>
       <td>22500</td>
    </tr>
    <tr>
        <td>ABLATION DU CE OROPHARYNX SA</td>
        <td>K1</td>
        <td>80</td>
        <td>750</td>
        <td>60000</td>
    </tr>
    <tr>
        <td>ABLATION DU CE AURICULAIRE SA</td>
        <td>4</td>
        <td>22</td>
        <td>750</td>
        <td>16500</td>
    </tr>
    <tr>
        <td>ABLATION DE KYSTE</td>
        <td>K4</td>
        <td>160</td>
        <td>750</td>
        <td>120000</td>
    </tr>
    <tr>
        <td>ABLATION DE CORPS ETRANGERS D</td>
        <td>K1</td>
        <td>22</td>
        <td>750</td>
        <td>16500</td>
    </tr>
    <tr>
        <td>ABLATIONDE DU CE DE L'OESOPHAGE</td>
        <td>K4</td>
        <td>50</td>
        <td>750</td>
        <td>37500</td>
    </tr>
     <tr>
        <td>ADENADECTOMIE</td>
        <td>K4</td>
        <td>68</td>
        <td>750</td>
        <td>51000</td>
     </tr>
     <tr>
        <td>ADENECTOMIE SOUS MAXILLAIRE SO</td>
        <td>K4</td>
        <td>120</td>
        <td>750</td>
        <td>90000</td>
     </tr>
     <tr>
        <td>ADENOAMYDALECTOMIE</td>
        <td>K4</td>
        <td>140</td>
        <td>750</td>
        <td>105000</td>
     </tr>
     <tr>
        <td>AMYGDALECTOMIE</td>
        <td>K4</td>
        <td>108</td>
        <td>750</td>
        <td>81000</td>
     </tr>
     <tr>
        <td>BIOPSIE A LA CHAISE</td>
        <td>K1</td>
        <td>22</td>
        <td>750</td>
        <td>16500</td>
     </tr>
     <tr>
        <td>CONSULTATION ORL</td>
        <td>C1</td>
        <td>1</td>
        <td>5250</td>
        <td>5250</td>
     </tr>
     <tr>
        <td>COMPLEMENT CONSULTATION REFE</td>
        <td>C7</td>
        <td>1</td>
        <td>100</td>
        <td>100</td>
     </tr>
     <tr>
        <td>CELLULITE</td>
        <td>K4</td>
        <td>30</td>
        <td>750</td>
        <td>22500</td>
     </tr>
     <tr>
        <td>COLOBOMA</td>
        <td>K4</td>
        <td>50</td>
        <td>750</td>
        <td>37500</td>
     </tr>
     <tr>
        <td>EXERESE DE KYSTE</td>
        <td>K4</td>
        <td>160</td>
        <td>750</td>
        <td>120000</td>
     </tr>
     <tr>
        <td>EXTRATION BDC/O</td>
        <td>K4</td>
        <td>3</td>
        <td>750</td>
        <td>2250</td>
     </tr>
     <tr>
        <td>FREIN DE LANGUE</td>
        <td>K4</td>
        <td>20</td>
        <td>750</td>
        <td>15000</td>
     </tr>
     <tr>
        <td>INCISION DRAINAGE PHLEGMON PER</td>
        <td>K4</td>
        <td>20</td>
        <td>750</td>
        <td>15000</td>
     </tr>
     <tr>
        <td>INCISION ABCES</td>
        <td>K4</td>
        <td>13</td>
        <td>750</td>
        <td>9750</td>
     </tr><tr>
        <td>INFILTRATION LOCAL</td>
        <td>K4</td>
        <td>11</td>
        <td>750</td>
        <td>8250</td>
     </tr>
     <tr>
        <td>INFILTRATION CH</td>
        <td>K4</td>
        <td>20</td>
        <td>750</td>
        <td>15000</td>
     </tr>
     <tr>
        <td>KYSTE</td>
        <td>K1</td>
        <td>160</td>
        <td>750</td>
        <td>120000</td>
     </tr>
     <tr>
        <td>LARYNGOSCOPIE EN SUSPENSION</td>
        <td>K4</td>
        <td>68</td>
        <td>750</td>
        <td>51000</td>
     </tr>
     <tr>
        <td>LARYNGOSCOPIE EN SUSPENSION<</td>
        <td>K4</td>
        <td>90</td>
        <td>750</td>
        <td>67000</td>
     </tr>
     <tr>
        <td>LAVAGE OU ASPIRATION OREILLE</td>
        <td>K4</td>
        <td>3</td>
        <td>750</td>
        <td>2250</td>
     </tr>
     <tr>
        <td>POLYPE DU MEAT NASAL</td>
        <td>K1</td>
        <td>150</td>
        <td>750</td>
        <td>112500</td>
     </tr>
     <tr>
        <td>SINUSITE MAXILLAIRE</td>
        <td>K1</td>
        <td>80</td>
        <td>750</td>
        <td>60000</td>
     </tr>
     <tr>
        <td>SOUS MAXILECTOMIE</td>
        <td>K4</td>
        <td>160</td>
        <td>750</td>
        <td>120000</td>
     </tr>
     <tr>
        <td>TEMPONEMENT INTERIEUR DU NEZ</td>
        <td>K4</td>
        <td>16</td>
        <td>750</td>
        <td>12000</td>
     </tr>
     <tr>
        <td>THYRODECTOMIE</td>
        <td>K1</td>
        <td>240</td>
        <td>750</td>
        <td>180000</td>
     </tr>
     <tr>
        <td>TRACHEOCTOMIE</td>
        <td>K4</td>
        <td>60</td>
        <td>750</td>
        <td>45000</td>
     </tr>
   </table>
    
</body>
</html>